services:
  - type: web
    name: wolf-game
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: false
        value: "10000"
      - key: GROQ_API_KEY
        sync: false
